### PR TITLE
wallpaper saving function + minor cleanup

### PR DESCRIPTION
**Pull request by dx3-dx3**
I moved some of your calls next to SetFromURL into a function of it's own (goSetWallpaper) since clearWindowsWallpaperCache and the macOS cleanup were being called every time. Also added a config flag saveLocally to save wallpapers into a download directory next to the exe and the accompanying function saveWallpaperLocally

Once again have not tested on windows but, i'll do that soon

### CODE REVIEW

**Comment by dx3-dx3** [comment]
crashes on windows. don't merge

**Comment by dx3-dx3** [comment]
oh shoot, I actually found a bug. on win10 if discord is not open and rich presence is enabled in config, the app will just close out.

**Comment by dx3-dx3** [comment]
> crashes on windows. don't merge

Ignore this, I submitted an issue. Tested on windows and it works! :)

**Comment by pupgray** [comment]
Spaces => tabs?

☢️ WAR DECLARED ☢️

**Review by oddpawsx — APPROVED** [review]
LGTM; for future PRs, mind to keep bug fixes and feature adds as separate PRs/issues? Makes it easier to review and track changes.

**Pull request merged**
